spring.application.name=demo1
server.port=8080

# Konfiguracja H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Konsola H2 dost?pna pod /h2-console
spring.h2.console.enabled=true

# Automatyczne tworzenie tabel
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true